[build]
  command = "CI= npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  for = "/Vehiculos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/Destinos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 